name: Sync Repo to Microsoft Fabric Workspace

on:
  push:
    branches:
      - main
    paths:
      - deploy/notebook/**/*.ipynb

env:
  TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
  CLIENT_ID: ${{ secrets.FABRIC_ID }}
  CLIENT_SECRET: ${{ secrets.FABRIC_SECRET_TOKEN }}
  WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}
  SUBSCRIPTION_ID: ${{ secrets.FABRIC_ACCESS_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get OAuth2 token
        id: auth
        run: |
          echo "Getting token..."
          TOKEN=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{ env.CLIENT_ID }}&client_secret=${{ env.CLIENT_SECRET }}&scope=https://api.fabric.microsoft.com/.default" \
            "https://login.microsoftonline.com/${{ env.TENANT_ID }}/oauth2/v2.0/token" | jq -r '.access_token')

          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Sync files to Microsoft Fabric workspace
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
          WORKSPACE_ID: ${{ env.WORKSPACE_ID }}
        run: |
          set -e

          # Remove /files from API base URL
          API_BASE="https://api.fabric.microsoft.com/v1/workspaces/${WORKSPACE_ID}/items"

          urlencode() {
            python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$1"
          }

          for FILE in $(git ls-files); do
            echo "Processing $FILE..."

            ENCODED_FILE=$(urlencode "$FILE")

            # Check if file exists by GET (adjusted URL)
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Bearer $TOKEN" \
              "$API_BASE/$ENCODED_FILE")

            CONTENT=$(base64 "$FILE" | tr -d '\n')

            if [ "$HTTP_STATUS" = "200" ]; then
              echo "File exists. Updating $FILE ..."
              RESPONSE=$(curl -s -w "\n%{http_code}" -X PUT -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
                -d "{\"content\":\"$CONTENT\"}" \
                "$API_BASE/$ENCODED_FILE")

              HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
              BODY=$(echo "$RESPONSE" | sed '$d')

              if [[ "$HTTP_CODE" =~ ^2 ]]; then
                echo "✅ Updated $FILE successfully. Status: $HTTP_CODE"
              else
                echo "❌ Failed to update $FILE. Status: $HTTP_CODE, Response: $BODY"
              fi
            else
              echo "File does not exist. Creating $FILE ..."
              RESPONSE=$(curl -s -w "\n%{http_code}" -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
                -d "{\"fileName\":\"$FILE\", \"content\":\"$CONTENT\"}" \
                "$API_BASE")

              HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
              BODY=$(echo "$RESPONSE" | sed '$d')

              if [[ "$HTTP_CODE" =~ ^2 ]]; then
                echo "✅ Created $FILE successfully. Status: $HTTP_CODE"
              else
                echo "❌ Failed to create $FILE. Status: $HTTP_CODE, Response: $BODY"
              fi
            fi
          done
