name: Sync Repo to Microsoft Fabric Workspace

on:
  push:
    branches:
      - main
    paths:
      - deploy/notebook/**/*.ipynb

env:
  WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}
  FABRIC_ACCESS_TOKEN: ${{ secrets.FABRIC_ACCESS_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Sync notebooks to Microsoft Fabric workspace
        env:
          TOKEN: ${{ env.FABRIC_ACCESS_TOKEN }}
          WORKSPACE_ID: ${{ env.WORKSPACE_ID }}
        run: |
          set -ex

          API_BASE="https://api.fabric.microsoft.com/v1/workspaces/${WORKSPACE_ID}/items"

          FILES=$(find deploy/notebook -name '*.ipynb')

          echo "Files to process: $FILES"

          if [ -z "$FILES" ]; then
            echo "No notebook files detected to upload, exiting."
            exit 0
          fi

          for FILE in $FILES; do
            echo "Processing $FILE..."

            DISPLAY_NAME=$(basename "$FILE" .ipynb)
            FILE_NAME="${DISPLAY_NAME}.ipynb"

            CONTENT_BASE64=$(base64 -w 0 "$FILE")

            PAYLOAD=$(jq -n \
              --arg dn "$DISPLAY_NAME" \
              --arg fn "$FILE_NAME" \
              --arg payload "$CONTENT_BASE64" \
              '{
                displayName: $dn,
                type: "Notebook",
                definition: {
                  format: "ipynb",
                  parts: [
                    {
                      path: $fn,
                      payload: $payload,
                      payloadType: "InlineBase64"
                    }
                  ]
                }
              }')

            echo "Uploading notebook: $DISPLAY_NAME"

            RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
              -H "Authorization: Bearer $TOKEN" \
              -H "Content-Type: application/json" \
              --data "$PAYLOAD" \
              "$API_BASE")

            HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
            BODY_RESP=$(echo "$RESPONSE" | sed '$d')

            echo "HTTP status: $HTTP_CODE"
            echo "Response body: $BODY_RESP"

            if [[ "$HTTP_CODE" =~ ^2 ]]; then
              echo "✅ Successfully uploaded $FILE"
            else
              echo "❌ Failed to upload $FILE"
              exit 1
            fi
          done
