name: Check Workspace Access

on: [workflow_dispatch]  # Allows manual trigger

jobs:
  check-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workspace Access
        env:
          WORKSPACE_ID: 0fde94f2-391e-42c0-bc8c-f29f17cac5f6
          ACCESS_TOKEN: 958077ec-bae1-4bda-b9a2-2116158d5879
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://api.example.com/workspaces/$WORKSPACE_ID/status")
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Workspace $WORKSPACE_ID is reachable."
          else
            echo "Failed to reach workspace $WORKSPACE_ID. HTTP status: $RESPONSE"
            exit 1
          fi
