name: Deploy Jupyter Notebook to QA-Finance Workspaces after Merge
on:
  push:
    branches:
      - mss-finance-edh-dev
    paths:
      - deploy/notebook/**/*.ipynb

jobs:
  deploy_to_uat_after_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure Access Token
        run: echo "AZURE_ACCESS_TOKEN=${{ secrets.AZURE_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33

      - name: Process and Deploy Notebooks
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            stackfile=$(echo $file | cut -f3 -d'/')
            echo "Processing file: $stackfile"
            echo $(cat deploy/notebook/$stackfile)
            echo "Converting the python code"
            sed 's/53c6f1fd-24c3-4ab6-b9f2-a283c3bb102c/958077ec-bae1-4bda-b9a2-2116158d5879/g' deploy/notebook/$stackfile > deploy/notebook_base64_tmp.txt
            sed 's/654d6099-5fef-4a37-90b2-c07d16f3f88a/0fde94f2-391e-42c0-bc8c-f29f17cac5f6/g' deploy/notebook_base64_tmp.txt > deploy/notebook_base64_tmp1.txt
            python -m base64 -e deploy/notebook_base64_tmp1.txt > deploy/notebook_base64_tmp1_base64.txt
            payload=$(cat deploy/notebook_base64_tmp1_base64.txt)
            echo "Payload content: $payload"

            nbfile=$(echo $stackfile | cut -f1 -d'.')
            echo "Notebook name will be: $nbfile"
            
            jq --arg val "$nbfile" '.displayName = $val' deploy/template.json > deploy/temp1.json
            jq --arg payloadValue "$payload" '.definition.parts[0].payload = $payloadValue' deploy/temp1.json > deploy/final.json
            
            echo "Displaying temp1.json"
            cat deploy/temp1.json
            echo "Displaying final.json"
            cat deploy/final.json
            
            finaljson=$(cat deploy/final.json)

            curl --location 'https://api.fabric.microsoft.com/v1/workspaces/654d6099-5fef-4a37-90b2-c07d16f3f88a/updateDefinition' \
              --header 'Content-Type: application/json' \
              --header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
              --data "$finaljson"
          done
