name: Deploy notebook garvita

on:
  push:
    branches:
      - main
    paths:
      - deploy/notebook/**/*.ipynb

jobs:
  deploy_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up environment variables
        run: |
          echo "AZURE_ACCESS_TOKEN=${{ secrets.AZURE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "FABRIC_WORKSPACE_ID=${{ secrets.FABRIC_WORKSPACE_ID }}" >> $GITHUB_ENV

      - name: Get changed .ipynb files
        id: changed-files
        uses: tj-actions/changed-files@v33
        with:
          files: |
            deploy/notebook/**/*.ipynb

      - name: Deploy changed notebooks to Microsoft Fabric
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "📘 Processing: $file"

            # Extract notebook name without extension
            filename=$(basename "$file")
            notebook_name="${filename%.ipynb}"

            echo "🧾 Notebook name: $notebook_name"

            # Encode notebook in base64 (no line wrapping)
            base64_content=$(base64 -w 0 "$file")

            # Inject notebook name and payload into template
            jq --arg name "$notebook_name" \
               --arg payload "$base64_content" \
               '.displayName = $name | .definition.parts[0].payload = $payload' \
               deploy/template.json > deploy/final.json

            # Send to Microsoft Fabric
            echo "🚀 Deploying $filename to Fabric workspace..."

            response=$(curl --silent --show-error --fail --location \
              --header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
              --header "Content-Type: application/json" \
              --data "@deploy/final.json" \
              "https://api.fabric.microsoft.com/v1/workspaces/$FABRIC_WORKSPACE_ID/items")

            echo "✅ Successfully deployed: $filename"
          done
