POST https://api.fabric.microsoft.com/v1/workspaces/%7BworkspaceId%7D/notebooks/%7BnotebookId%7D/updateDefinition
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSIsImtpZCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSJ9.eyJhdWQiOiJodHRwczovL2FwaS5mYWJyaWMubWljcm9zb2Z0LmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzU1ZWE2MTk2LTcwYjktNDQxMS05MmY1LTA0YTU0NzkxZjEyMC8iLCJpYXQiOjE3NDI4OTc3MDksIm5iZiI6MTc0Mjg5NzcwOSwiZXhwIjoxNzQyOTAyMzAxLCJhY2N0IjowLCJhY3IiOiIxIiwiYWlvIjoiQWFRQVcvOFpBQUFBU1ZVLzZxMDUwdlhmck44Vy93UGVwS3ZCWVNzNkpFa0hpdjBHSlZIT2RTYmYzR2MwTDQzSkduNGZ5T1M3RkR5RUVFYTZBMHJ5VlR5T01QZ0JhcEhOZnF1SjNyYnF2NFRJM3FGaWRzUG9UWjNPWkR6Y3JWdkwySlBQR2NVQ2hlZUpmWGlVZm84ZDhBeFg3TGJkeFRHUEhtaE5WOTAveTk5RTkyWHZlT0ZPUjlMTCtLSC9mZHB3UjZhTXJZaHlwK1NaelJSQm1jVC9qTmc2c2xqT3pLZ2YyUT09IiwiYW1yIjpbInJzYSIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiNmJiM2RmMDQtNTFlNi00MTk3LTk5NGUtOWJkMWEwMDRiODM5IiwiZmFtaWx5X25hbWUiOiJLdW1iaGFyZSIsImdpdmVuX25hbWUiOiJTYWtzaGkiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNjcuMTAzLjIuMTE5IiwibmFtZSI6Ikt1bWJoYXJlLCBTYWtzaGkiLCJvaWQiOiIzOWM5NzA3Ny0zMDUxLTQ1M2EtOTE1Mi0wNmFhNGZhY2UyMDciLCJwdWlkIjoiMTAwMzIwMDM3OUU3MzIyQSIsInJoIjoiMS5BVnNBbG1IcVZibHdFVVNTOVFTbFI1SHhJQWtBQUFBQUFBQUF3QUFBQUFBQUFBRDVBRFJiQUEuIiwic2NwIjoiQXBwLlJlYWQuQWxsIENhcGFjaXR5LlJlYWQuQWxsIENhcGFjaXR5LlJlYWRXcml0ZS5BbGwgQ29ubmVjdGlvbi5SZWFkLkFsbCBDb25uZWN0aW9uLlJlYWRXcml0ZS5BbGwgQ29udGVudC5DcmVhdGUgRGFzaGJvYXJkLlJlYWQuQWxsIERhc2hib2FyZC5SZWFkV3JpdGUuQWxsIERhdGFmbG93LlJlYWQuQWxsIERhdGFmbG93LlJlYWRXcml0ZS5BbGwgRGF0YXNldC5SZWFkLkFsbCBEYXRhc2V0LlJlYWRXcml0ZS5BbGwgR2F0ZXdheS5SZWFkLkFsbCBHYXRld2F5LlJlYWRXcml0ZS5BbGwgSXRlbS5FeGVjdXRlLkFsbCBJdGVtLkV4dGVybmFsRGF0YVNoYXJlLkFsbCBJdGVtLlJlYWRXcml0ZS5BbGwgSXRlbS5SZXNoYXJlLkFsbCBPbmVMYWtlLlJlYWQuQWxsIE9uZUxha2UuUmVhZFdyaXRlLkFsbCBQaXBlbGluZS5EZXBsb3kgUGlwZWxpbmUuUmVhZC5BbGwgUGlwZWxpbmUuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZFdyaXRlLkFsbCBSZXBydC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkV3JpdGUuQWxsIFRlbmFudC5SZWFkLkFsbCBUZW5hbnQuUmVhZFdyaXRlLkFsbCBVc2VyU3RhdGUuUmVhZFdyaXRlLkFsbCBXb3Jrc3BhY2UuR2l0Q29tbWl0LkFsbCBXb3Jrc3BhY2UuR2l0VXBkYXRlLkFsbCBXb3Jrc3BhY2UuUmVhZC5BbGwgV29ya3NwYWNlLlJlYWRXcml0ZS5BbGwiLCJzaWQiOiIwMDIwM2ExOS01NzU0LTFmYTktNmM4Zi03MzZiNTc3Mjc3N2IiLCJzaWduaW5fc3RhdGUiOlsiaW5rbm93bm50d2siLCJrbXNpIl0sInN1YiI6IkV4WlUyRnRHaEVNSFEyQXFjTjlnbGIxTWFxQWdFVUNrVDkzcldfMkVuc1UiLCJ0aWQiOiI1NWVhNjE5Ni03MGI5LTQ0MTEtOTJmNS0wNGE1NDc5MWYxMjAiLCJ1bmlxdWVfbmFtZSI6InNha3NoaS5rdW1iaGFyZUBzdHJhdGFjZW50LmNvbSIsInVwbiI6InNha3NoaS5rdW1iaGFyZUBzdHJhdGFjZW50LmNvbSIsInV0aSI6InhGYzZKQ0pLMFVtVVY5NWlCRVJpQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDI4IiwieG1zX3BsIjoiZW4tVVMifQ.VELRfMMboVgMW3eEA5l4xlK13aoqKlzmxovMpMWdZhxER63rOKhjJvTn2N75cDWpMmNbUXVwCNRN5PZkc9_n2ltFqpHNfIhXT5u0-LD8JXfElrQMXzOru4LeJGmVaWQnZkccKSHeeT0zvSi9n7MRgeQhdceXrg7Cbxu2wfSNkS95kT23SbyWHoh6HV7uRNzXy_34HXsVfi8J0pk471Qju-h1ERiNvCQbN-gw0xS0fws2TRQeSFJd3hK9HgxlxPb1y9nc2Epf80IPWMuEL_hlCZ8KocnLg7FbafKaPwXjQDCzp6Q3A8FVK4O92-GZ-A0wQRBCQjb1B7C5vICif2px5g
Content-type: application/json



name: Deploy Jupyter Notebook to QA-Finance Workspaces after Merge
on:
  push:
    branches:
      - mss-finance-edh-dev
    paths:
      - deploy/notebook/**/*.ipynb

jobs:
  deploy_to_uat_after_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure Access Token
        run: echo "AZURE_ACCESS_TOKEN=${{ secrets.AZURE_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33

      - name: Process and Deploy Notebooks
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            stackfile=$(echo $file | cut -f3 -d'/')
            echo "Processing file: $stackfile"
            echo $(cat deploy/notebook/$stackfile)
            cat deploy/notebook/$stackfile | jq || cat deploy/notebook/$stackfile
            echo "Converting the python code"
            sed 's/53c6f1fd-24c3-4ab6-b9f2-a283c3bb102c/958077ec-bae1-4bda-b9a2-2116158d5879/g' deploy/notebook/$stackfile > deploy/notebook_base64_tmp.txt
            sed 's/654d6099-5fef-4a37-90b2-c07d16f3f88a/0fde94f2-391e-42c0-bc8c-f29f17cac5f6/g' deploy/notebook_base64_tmp.txt > deploy/notebook_base64_tmp1.txt
            base64 -w 0 deploy/notebook_base64_tmp1.txt > deploy/notebook_base64_tmp1_base64.txt
            payload=$(cat deploy/notebook_base64_tmp1_base64.txt)
            echo "Payload content: $payload"

            nbfile=$(echo $stackfile | cut -f1 -d'.')
            echo "Notebook name will be: $nbfile"
            
            jq --arg val "$nbfile" '.displayName = $val' deploy/template.json > deploy/temp1.json
            jq --arg payloadValue "$payload" '.definition.parts[0].payload = $payloadValue' deploy/temp1.json > deploy/final.json
            
            echo "Displaying temp1.json"
            cat deploy/temp1.json
            echo "Displaying final.json"
            cat deploy/final.json | jq

            finaljson=$(cat deploy/final.json)

            curl -v --location 'https://api.fabric.microsoft.com/v1/workspaces/654d6099-5fef-4a37-90b2-c07d16f3f88a/synapsenotebooks/14067047-2d6f-4227-a7ba-e957f8289f8b/updateDefinition' \
             --header 'Content-Type: application/json' \
             --header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
             --data "@deploy/final.json"
             
          done
