---
name: Deploy Jupyter Notebook to QA-Finance Workspaces after Merge
on:
  push:
    branches:
      - mss-finance-edh-dev
    path:
      - deploy/notebook/**.ipynb
jobs:
  deploy_to_uat_after_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Azure Access Token
        run: echo "AZURE_ACCESS_TOKEN=${{ secrets.AZURE_ACCESS_TOKEN }}" >> $GITHUB_ENV
      # - name: Azure Login
      #   env:
      #     AZURE_USERNAME: ${{ secrets. AZURE_USERNAME}}
      #     AZURE_PASSWORD: ${{ secrets. AZURE_PASSWORD }}
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      #   run: >
      #     az login --username $AZURE_USERNAME --password $AZURE_PASSWORD
      #     echo "::set-env name=AZURE_ACCESS_TOKEN::$(az account get-access-token --resource 'https://api.fabric.microsoft.com' --query 'accessToken' -o tsv)" 
      #     echo "Access Token: ${{ env.AZURE_ACCESS_TOKEN }}"		
      # - name: Print Access Token
      #   run: |
      #     echo "${{ env.AZURE_ACCESS_TOKEN }}"		
      # - name: Use Access Token in Workfloww
      #   uses:
      #     AZURE_ACCESS_TOKEN: ${{ secrets. AZURE_ACCESS_TOKEN}}		
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
      # - name: Make API Call
      #   env:
      #     # ID_TOKEN: ${{ secrets.MYID_TOKEN }}
      #     AZURE_ACCESS_TOKEN: ${{ secrets.AZURE_ACCESS_TOKEN }}
        run: >
          #for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # stackfile=$(echo $file | cut -f2 -d'/')
          # parameter_value=$(cat deploy/$stackfile)
          # curl --location 'https://api.fabric.microsoft.com/v1/workspaces/1b5bf1f0-7742-49bb-a4b6-8d2720a82173/notebooks' \ 
          #   --header 'Content-Type: application/json' \
          #	--header 'Host: graph.microsoft.com' \
          #	--header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
          #   --data "$parameter_value"
          # done

          #python -m pip install --upgrade pip
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          stackfile=$(echo $file | cut -f3 -d'/')
          echo $stackfile
          parameter_value=$(cat deploy/notebook/$stackfile)
          echo "converting the python code"
          sed 's/53c6f1fd-24c3-4ab6-b9f2-a283c3bb102c/958077ec-bae1-4bda-b9a2-2116158d5879/g' deploy/notebook/$stackfile > deploy/notebook_ba 
          sed 's/654d6099-5fef-4a37-90b2-c07d16f3f88a/0fde94f2-391e-42c0-bc8c-f29f17cac5f6/g' deploy/notebook_base64_tmp_1.txt > deploy/noteb 
          python -m base64 -e deploy/notebook_base64_tmp.txt > deploy/notebook_base64_tmp1.txt
          echo "print of deploy/filename"
          cat deploy/notebook_base64_tmp1.txt
          echo "print of filename"
          python -m base64 -e deploy/notebook/$stackfile > notebook_base64.txt
          payload=$(cat deploy/notebook_base64_tmp1.txt)
          echo "payload"
          echo $payload
          #new##########
          #Pythonfile would be like below
          nbfile=$(echo $stackfile | cut -f1 -d'.')
          echo "Notebook name will be"
          echo $nbfile
          #curl --location 'https://api.fabric.microsoft.com/v1/workspaces/654d6099-5fef-4a37-90b2-c07d16f3f88a/items' \
          # --header 'Content-Type: application/json' \
          # --header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
          # --data "$parameter_value"	
          #NEW
          jq --arg val "$nbfile" '.displayName = $val' deploy/template.json > deploy/temp1.json
          jq --arg payloadValue "$payload" .definition.parts[0].payload = $payloadValue' deploy/temp1.json > deploy/final.json 
          echo "displaying temp1.json"
          echo $(cat deploy/temp1.json)
          echo "displaying Final.json"
          echo $(cat deploy/final.json)
          finaljson=$(cat deploy/final.json)
          #--data '{"displayName":"$(nbfile)","type":"Notebook","definition":{"format":"ipynb", "parts": ["path":"artifact.content.ipynb","payload":"$(payload)","payloadType":"InlineBase64"}]}}' 
          curl --location 'https://api.fabric.microsoft.com/v1/workspaces/1b5bf1f0-7742-49bb-a4b6-8d2728a82173/items' 
            --header 'Content-Type: application/json' \
            --header 'Host: graph.microsoft.com' \
            --header "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
            --data "$finaljson"
          done
